apiVersion: v1
kind: PersistentVolume
metadata:
  name: ledger-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: ledger-disk
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ledger-pvc
  namespace: ledger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi